<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Tiferet.Core\Tiferet.Core.csproj" />
    <ProjectReference Include="..\..\src\Tiferet.Domain\Tiferet.Domain.csproj" />
    <ProjectReference Include="..\..\src\Tiferet.Events\Tiferet.Events.csproj" />
    <ProjectReference Include="..\..\src\Tiferet.Interfaces\Tiferet.Interfaces.csproj" />
    <ProjectReference Include="..\..\src\Tiferet.Mappers\Tiferet.Mappers.csproj" />
    <ProjectReference Include="..\..\src\Tiferet.DependencyInjection\Tiferet.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\Tiferet.Utilities\Tiferet.Utilities.csproj" />
  </ItemGroup>

</Project>
