cli:
  cmds:
    calc:
      add:
        Name: Add Number Command
        Description: Adds two numbers.
        Arguments:
          - NameOrFlags:
              - a
            Description: The first number to add.
          - NameOrFlags:
              - b
            Description: The second number to add.
      subtract:
        Name: Subtract Number Command
        Description: Subtracts one number from another.
        Arguments:
          - NameOrFlags:
              - a
            Description: The number to subtract from.
          - NameOrFlags:
              - b
            Description: The number to subtract.
      multiply:
        Name: Multiply Number Command
        Description: Multiplies two numbers.
        Arguments:
          - NameOrFlags:
              - a
            Description: The first number to multiply.
          - NameOrFlags:
              - b
            Description: The second number to multiply.
      divide:
        Name: Divide Number Command
        Description: Divides one number by another.
        Arguments:
          - NameOrFlags:
              - a
            Description: The numerator.
          - NameOrFlags:
              - b
            Description: The denominator.
      sqrt:
        Name: Square Root Command
        Description: Calculates the square root of a number.
        Arguments:
          - NameOrFlags:
              - a
            Description: The number to square root.
