services:
  add_number_event:
    AssemblyName: Tiferet.Examples.Calculator
    TypeName: Tiferet.Examples.Calculator.Events.AddNumber
  subtract_number_event:
    AssemblyName: Tiferet.Examples.Calculator
    TypeName: Tiferet.Examples.Calculator.Events.SubtractNumber
  multiply_number_event:
    AssemblyName: Tiferet.Examples.Calculator
    TypeName: Tiferet.Examples.Calculator.Events.MultiplyNumber
  divide_number_event:
    AssemblyName: Tiferet.Examples.Calculator
    TypeName: Tiferet.Examples.Calculator.Events.DivideNumber
  exponentiate_number_event:
    AssemblyName: Tiferet.Examples.Calculator
    TypeName: Tiferet.Examples.Calculator.Events.ExponentiateNumber
const: {}
