errors:
  INVALID_INPUT:
    Name: Invalid Numeric Input
    Messages:
      - Lang: en_US
        Text: 'Value {value} must be a number'
      - Lang: es_ES
        Text: 'El valor {value} debe ser un numero'
  DIVISION_BY_ZERO:
    Name: Division By Zero
    Messages:
      - Lang: en_US
        Text: 'Cannot divide by zero'
      - Lang: es_ES
        Text: 'No se puede dividir por cero'
