using System.Reflection;
using Tiferet.Core;
using Tiferet.Domain;

namespace Tiferet.Mappers;

/// <summary>
/// Base class for mutable domain aggregates.
/// Wraps an immutable <typeparamref name="TDomain"/> record and exposes
/// validated mutation via <see cref="SetAttribute"/>.
/// </summary>
/// <typeparam name="TDomain">The domain record type.</typeparam>
public abstract class Aggregate<TDomain> where TDomain : DomainObject
{
    /// <summary>The underlying immutable domain record.</summary>
    public TDomain Domain { get; protected set; }

    /// <summary>
    /// Initializes the aggregate with the given domain record.
    /// </summary>
    /// <param name="domain">The domain record to wrap.</param>
    protected Aggregate(TDomain domain)
    {
        Domain = domain;
    }

    /// <summary>
    /// Update a property on the underlying domain record by name,
    /// producing a new record via reflection-based <c>with</c> cloning.
    /// Raises <see cref="TiferetException"/> with
    /// <see cref="ErrorCodes.InvalidModelAttribute"/> if the property does not exist.
    /// </summary>
    /// <param name="attribute">The property name to update (PascalCase).</param>
    /// <param name="value">The new value to assign.</param>
    public void SetAttribute(string attribute, object? value)
    {
        // Resolve the property on the domain record type.
        var property = typeof(TDomain).GetProperty(
            attribute,
            BindingFlags.Public | BindingFlags.Instance);

        // Reject unknown attribute names.
        if (property is null)
        {
            throw new TiferetException(
                ErrorCodes.InvalidModelAttribute,
                $"Property '{attribute}' does not exist on {typeof(TDomain).Name}.",
                ("attribute", attribute));
        }

        // Clone the record with the updated property via the compiler-generated <Clone>$ method.
        Domain = CloneWith(property, value);
    }

    /// <summary>
    /// Clone the domain record, setting the specified property to a new value.
    /// Uses the compiler-generated <c>&lt;Clone&gt;$</c> method on records.
    /// </summary>
    private TDomain CloneWith(PropertyInfo property, object? value)
    {
        // Use the <Clone>$ method generated by the compiler for records.
        var cloneMethod = typeof(TDomain).GetMethod("<Clone>$", BindingFlags.Public | BindingFlags.Instance)
            ?? throw new InvalidOperationException(
                $"{typeof(TDomain).Name} does not have a record clone method.");

        var clone = (TDomain)cloneMethod.Invoke(Domain, null)!;

        // Set the property on the clone (record init-only setters are accessible via reflection).
        property.SetValue(clone, value);

        return clone;
    }
}
