<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Tiferet.Core\Tiferet.Core.csproj" />
    <ProjectReference Include="..\Tiferet.Domain\Tiferet.Domain.csproj" />
    <ProjectReference Include="..\Tiferet.Interfaces\Tiferet.Interfaces.csproj" />
    <ProjectReference Include="..\Tiferet.Mappers\Tiferet.Mappers.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
